### PR TITLE
Updating VideoIndexer and Callback Wofkflow

### PR DESCRIPTION
**Pull request by uday31in**
BlobSASURI-BlobFile response is failing to parse

image

### CODE REVIEW

**Comment by uday31in** [comment]
image

**Comment by uday31in** [comment]
image

**Comment by marvinbuss** [comment]
Great work Uday.
If you don't mind, can we test the ARM way of creating SAS tomorrow to not rely on storage account keys?

I will open a PR against your PR so that we can validate and get that done.

**Review by marvinbuss — CHANGES_REQUESTED** [review]
I would propose to remove changes for the `Videoindexer-Workflow` from this PR and just use changes proposed here: https://github.com/Azure/ai-hub/pull/164
I am good with merging changes for the `Callback-Workflow`.

**Pull request closed without merging**
