### PR TITLE
Fix Bugs

### PR DESCRIPTION
**Pull request by marvinbuss**
**Proposed changes**:
- Add Web Connections Access Policies via azapi provider instead of using ARM templates.
- Add `Storage Account Contributor` Permission for Logic App to generate SAS tokens using ARM REST API (Reference: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/tutorial-windows-vm-access-storage-sas).
- Switch to ARM API for SAS token and scope SAS token to blob instead of the account. Parse the response using a JSON activity.
- Limit SAS token validity to 3 hours. We can reduce this further over time in case the video indexer consistently require less time.
- Update authentication to rely on managed identities for managed APIs instead of keys.
- Update folder to which the trigger for the Video Indexer workflow listens to `concat(parameters('STORAGE_CONTAINER_NAME_RAW'),'/videos/{blobname}.{blobextension}')`. Now, it only checks for files uploaded into the `videos` directory. Reference: https://learn.microsoft.com/en-us/azure/connectors/connectors-create-api-azureblobstorage?tabs=standard#built-in-connector-trigger
- Parametrize Video Name in Video Indexer to ensure different names, in case the video gets processed  twice for some reason (e.g. service errors, reprocessing required, etc.). It will now use the current timestamp plus the original file name (e.g. `<timestamp>-<file-name>-<file extension>`).
- Add logic app app settings `WEBSITE_RUN_FROM_PACKAGE              = "1"` to ensure code deployed via CICD is being executed.
- Add role assignment `Logic Apps Standard Operator (Preview)` for Logic App to logic app resource scope to allow dynamically fetching the callback URI of other workflows.
- Add activities to workflow to dynamically fetch callback URI for Video Indexer activity and pass property to video indexer.
- Switch to node version 20 for Logic App Standard
- Update client cert mode from `Required` to `Optional`

### CODE REVIEW

**Comment by marvinbuss** [comment]
Video Indexer Result: 
image

**Comment by marvinbuss** [comment]
Workflow works as expected: 
image

**Review by marvinbuss — COMMENTED** [review]
LGTM! Ready for review.

**Review by uday31in — APPROVED** [review]

**Review by marvinbuss — COMMENTED** [review]
LGTM! Ready to get merged.

**Pull request merged**
